---

    - name: generate key pair
      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N /dev/null

    - name: fetch public key
      fetch:
        src: /root/.ssh/id_rsa.pub
        dest: tmp/
        flat: yes

    #- name: add master public key to slaves
     # authorized_key:
      #  user: root
       # key: "{{ lookup('file', 'tmp/id_rsa.pub') }}"




